name: 'Config Entity Example'
type: module
description: 'Demonstrates how to create a config entity type.'
package: Example modules
core_version_requirement: ^8.7.7 || ^9 || ^10
dependencies:
  - examples:examples

# Information added by Drupal.org packaging script on 2023-02-18
version: '3.0.4'
project: 'examples'
datestamp: 1676729672
